[agent]
  interval = "10s"
  flush_interval = "10s"

# Input : MQTT depuis HiveMQ Cloud
[[inputs.mqtt_consumer]]
  servers = ["ssl://f14a117fb9474a3a8d1ef491a81347ef.s1.eu.hivemq.cloud:8883"]
  topics = ["sensors/data"]
  username = "gerfou"
  password = "rGEm4M-!u"
  data_format = "json"
  json_name_key = "device"
  tag_keys = ["device"]
  json_time_key = "ts"
  json_time_format = "2006-01-02T15:04:05-0700"
  insecure_skip_verify = false

# Output : InfluxDB v2
[[outputs.influxdb_v2]]
  urls = ["http://influxdb:8086"]
  token = "echomesh-super-secret-token"
  organization = "echomesh"
  bucket = "sensors"
